version: "3.9"
networks:
  microservice-ecommerce:

services:
  application-gateway:
    image: "naveenbhardwaj/application-gateway:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9000:9000

  account-service:
    image: "naveenbhardwaj/account-service:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9001:9001

  auth-service:
    image: "naveenbhardwaj/auth-service:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9002:9002

  order-service:
    image: "naveenbhardwaj/order-service:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9003:9003

  payment-service:
    image: "naveenbhardwaj/payment-service:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9004:9004

  shipping-service:
    image: "naveenbhardwaj/shipping-service:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9005:9005

  inventory-management-service:
    image: "naveenbhardwaj/inventory-management-service:1.0.0"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - microservice-ecommerce
    ports:
      - 9006:9006
