version: "3.9"
services:
  jaeger:
      image: jaegertracing/all-in-one
      ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 14250:14250
        - 9411:9411

  discovery-service:
    image: "naveenbhardwaj/discovery-service:1.0.0"
    ports:
      - 8761:8761

  application-gateway:
    image: "naveenbhardwaj/application-gateway:1.0.0"
    ports:
      - 9000:9000

  account-service:
    image: "naveenbhardwaj/account-service:1.0.0"
    ports:
      - 9001:9001

  auth-service:
    image: "naveenbhardwaj/auth-service:1.0.0"
    ports:
      - 9002:9002

  order-service:
    image: "naveenbhardwaj/order-service:1.0.0"
    ports:
      - 9003:9003

  payment-service:
    image: "naveenbhardwaj/payment-service:1.0.0"
    ports:
      - 9004:9004

  shipping-service:
    image: "naveenbhardwaj/shipping-service:1.0.0"
    ports:
      - 9005:9005

  inventory-management-service:
    image: "naveenbhardwaj/inventory-management-service:1.0.0"
    ports:
      - 9006:9006
