version: "3.9"
networks:
  microservice-ecommerce:

services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - microservice-ecommerce
  jaeger:
    image: jaegertracing/all-in-one
    networks:
      - microservice-ecommerce
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  discovery-service:
    image: "naveenbhardwaj/discovery-service:1.0.0"
    networks:
      - microservice-ecommerce
    ports:
      - 8761:8761