spring:
  application:
    name: shipping-service

server:
  port: ${PORT:9005}
  servlet:
    context-path: /ship

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true